In [ ]:
import pandas as pd

In [ ]:
# read in the flower dataset
flower_df = pd.read_csv("/content/flower_dataset.csv")
flower_df.head()

,Unnamed: 0,sepal length,sepal width,petal length,petal width,label
0,0,6.1,2.8,4.0,1.3,Iris-versicolor
1,1,6.0,2.2,5.0,1.5,Iris-virginica
2,2,4.7,3.2,1.6,0.2,Iris-setosa
3,3,6.3,3.3,6.0,2.5,Iris-Virginica
4,4,5.3,3.7,1.5,0.2,Iris-setosa

In [ ]:
# drop the "Unnamed: 0"
flower_df = flower_df.drop("Unnamed: 0", axis = "columns")
# we also see that the labels are inconsistent
flower_df.head()

   sepal length  sepal width  petal length  petal width            label
0           6.1          2.8           4.0          1.3  Iris-versicolor
1           6.0          2.2           5.0          1.5   Iris-virginica
2           4.7          3.2           1.6          0.2      Iris-setosa
3           6.3          3.3           6.0          2.5   Iris-Virginica
4           5.3          3.7           1.5          0.2      Iris-setosa

In [ ]:
# the best way with this short dataset is probably to do it manually, but we can also do it automatically
num_flowers = len(flower_df)
for i in range(num_flowers):
  # access the label in each column
  label = flower_df.iloc[i, 4]
  # convert it all to lower case
  lower_label = label.lower()
  if ("setosa" in lower_label):
    flower_df.iloc[i, 4] = 0
  elif ("versicolor" in lower_label or "versicolour" in lower_label):
    flower_df.iloc[i, 4] = 1
  else:
    flower_df.iloc[i, 4] = 2

In [ ]:
# split into train and test X and y (separate 5 values for test)
train_X = flower_df.iloc[:-5,:4]
train_y = list(flower_df.iloc[:-5,4])
test_X = flower_df.iloc[-5:,:4]
test_y = list(flower_df.iloc[-5:,4])

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
# run logistic regression on the data
log_reg = LogisticRegression()
log_reg.fit(train_X, train_y)
log_reg.score(test_X, test_y)

1.0

In [ ]:
# read in the fraud dataset
fraud_df = pd.read_csv("/content/fraud_dataset.csv")
fraud_df.head()

   Unnamed: 0  amount  fraud
0           0     100      0
1           1     150      0
2           2     200      0
3           3    5000      1
4           4     130      0

In [ ]:
# drop the "Unnamed: 0"
fraud_df = fraud_df.drop("Unnamed: 0", axis = "columns")

In [ ]:
fraud_df
# we see two total examples of fraud, so data is limited
# SVM will probably work best, but more data would be great

    amount  fraud
0      100      0
1      150      0
2      200      0
3     5000      1
4      130      0
5      120      0
6      250      0
7      300      0
8      400      0
9      500      0
10     110      0
11     140      0
12     180      0
13    5100      1
14     135      0
15     125      0
16     270      0
17     320      0
18     420      0
19     520      0

In [ ]:
# split into train and test X and y (separate 5 values for test)
train_X = fraud_df.iloc[:-5,:1]
train_y = list(fraud_df.iloc[:-5,1])
test_X = fraud_df.iloc[-5:,:1]
test_y = list(fraud_df.iloc[-5:,1])

In [ ]:
from sklearn.svm import SVC

In [ ]:
clf = SVC()
clf.fit(train_X, train_y)
# all the values in test x and test y are not fraud in this unbalanced dataset
clf.score(test_X, test_y)

1.0

In [ ]:
internship_df = pd.read_csv("/content/internship_dataset.csv")
internship_df.head()

   Unnamed: 0  resume strength  gender  hired
0           0           16.150       1      1
1           1            3.393       0      0
2           2           10.921       0      1
3           3            9.521       0      0
4           4            9.384       1      0

In [ ]:
# drop the "Unnamed: 0"
internship_df = internship_df.drop("Unnamed: 0", axis = "columns")
internship_df.head()
print(internship_df)

    resume strength  gender  hired
0            16.150       1      1
1             3.393       0      0
2            10.921       0      1
3             9.521       0      0
4             9.384       1      0
5            16.513       0      1
6            23.868       0      1
7             8.242       0      0
8            15.456       1      0
9            20.362       0      0
10           15.784       1      1
11            9.710       0      0
12           22.715       1      1
13            2.759       0      0
14           17.128       1      1
15           14.337       1      0
16           25.637       1      1
17           10.290       0      0
18           18.214       1      1
19           13.627       0      0

In [ ]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()

# what's happening here is that the algorithm will learn to hire people based on the fact that they're male.
# gender is a protected attribute so it cannot be legally used for hiring
X = internship_df.iloc[:,:2]
y = internship_df.iloc[:,2]
log_reg.fit(X, y)

LogisticRegression()

In [ ]:
# here are the coefficients and we see a positive coeficient for the gender
log_reg.coef_

array([[0.33714673, 0.30157951]])

In [ ]:
internship_df = internship_df.drop("gender", axis = "columns")
internship_df.head()

   resume strength  hired
0           16.150      1
1            3.393      0
2           10.921      1
3            9.521      0
4            9.384      0

In [ ]:
# split into train and test X and y (separate 5 values for test)
train_X = internship_df.iloc[:-5,:1]
train_y = list(internship_df.iloc[:-5,1])
test_X = internship_df.iloc[-5:,:1]
test_y = list(internship_df.iloc[-5:,1])

In [ ]:
# run logistic regression on the data
log_reg = LogisticRegression()
log_reg.fit(train_X, train_y)
log_reg.score(test_X, test_y)

0.8