## MAIN LAB

In [1]:
# This automatically downloads modified_iris dataset from the aibridge website
!wget "https://aibridgecamp.github.io/assets/datasets/modified_iris.csv"

--2024-06-19 18:42:24--  https://aibridgecamp.github.io/assets/datasets/modified_iris.csv
Resolving aibridgecamp.github.io (aibridgecamp.github.io)... 185.199.108.153, 185.199.109.153, 185.199.110.153, ...
Connecting to aibridgecamp.github.io (aibridgecamp.github.io)|185.199.108.153|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://aibridge.us/assets/datasets/modified_iris.csv [following]
--2024-06-19 18:42:24--  https://aibridge.us/assets/datasets/modified_iris.csv
Resolving aibridge.us (aibridge.us)... 185.199.108.153, 185.199.109.153, 185.199.110.153, ...
Connecting to aibridge.us (aibridge.us)|185.199.108.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5144 (5.0K) [text/csv]
Saving to: ‘modified_iris.csv’

modified_iris.csv   100%[===================>]   5.02K  --.-KB/s    in 0s

2024-06-19 18:42:24 (51.6 MB/s) - ‘modified_iris.csv’ saved [5144/5144]

In [2]:
# standard reading procedure
opened_iris = open("/content/modified_iris.csv",'r')
iris_lines = opened_iris.readlines()
opened_iris.close()

# lets look at the first 5 lines
iris_lines[:5]

[',pedal length,pedal width,time when measured,cur weather,species\n',
 '0,1.4,0.2,8.438096672479016,3,0\n',
 '1,1.4,0.2,11.718959212196108,0,0\n',
 '2,1.3,0.2,9.344060890211455,1,0\n',
 '3,1.5,0.2,12.975979720838176,3,0\n']

In [3]:
# this removes first row of names
iris_lines.pop(0)
print(iris_lines)

['0,1.4,0.2,8.438096672479016,3,0\n', '1,1.4,0.2,11.718959212196108,0,0\n', '2,1.3,0.2,9.344060890211455,1,0\n', '3,1.5,0.2,12.975979720838176,3,0\n', '4,1.4,0.2,15.399046978463142,1,0\n', '5,1.7,0.4,8.996673215283565,0,0\n', '6,1.4,0.3,8.080913140011239,0,0\n', '7,1.5,0.2,15.91301916113,0,0\n', '8,1.4,0.2,13.781260782784647,1,0\n', '9,1.5,0.1,14.26600067734822,0,0\n', '10,1.5,0.2,10.422614444739098,4,0\n', '11,1.6,0.2,11.258255051444394,4,0\n', '12,1.4,0.1,16.957931755196086,0,0\n', '13,1.1,0.1,14.029312172009394,1,0\n', '14,1.2,0.2,7.5632414819886025,1,0\n', '15,1.5,0.4,11.500351989850571,1,0\n', '16,1.3,0.4,14.265060596809754,3,0\n', '17,1.4,0.3,9.522152969330811,1,0\n', '18,1.7,0.3,11.073328775324736,2,0\n', '19,1.5,0.3,11.512444539179668,4,0\n', '20,1.7,0.2,13.117798405400128,3,0\n', '21,1.5,0.4,10.05121258588883,4,0\n', '22,1.0,0.2,12.770635281849914,0,0\n', '23,1.7,0.5,14.896262399466314,1,0\n', '24,1.9,0.2,13.919784952040711,0,0\n', '25,1.6,0.2,14.322171756726775,2,0\n', '26,1.6,0.4,16.305400445459583,2,0\n', '27,1.5,0.2,10.224682844395677,4,0\n', '28,1.4,0.2,16.20263763676727,3,0\n', '29,1.6,0.2,14.359895868010698,0,0\n', '30,1.6,0.2,9.164512510754147,4,0\n', '31,1.5,0.4,8.725315819030271,1,0\n', '32,1.5,0.1,12.54238371284544,1,0\n', '33,1.4,0.2,15.046081115462941,3,0\n', '34,1.5,0.2,10.775045240163154,3,0\n', '35,1.2,0.2,10.836365336088821,3,0\n', '36,1.3,0.2,11.950513031508361,4,0\n', '37,1.4,0.1,9.663201294581624,2,0\n', '38,1.3,0.2,12.126547926317599,0,0\n', '39,1.5,0.2,13.510486084722531,3,0\n', '40,1.3,0.3,13.845505047834155,0,0\n', '41,1.3,0.3,13.256985914202538,3,0\n', '42,1.3,0.2,8.097623084805146,0,0\n', '43,1.6,0.6,10.323870438701316,2,0\n', '44,1.9,0.4,7.180225837325134,4,0\n', '45,1.4,0.3,10.122781714012895,1,0\n', '46,1.6,0.2,15.647279707525005,3,0\n', '47,1.4,0.2,7.466782980164871,3,0\n', '48,1.5,0.2,13.93047381075655,3,0\n', '49,1.4,0.2,10.82614504749116,2,0\n', '50,4.7,1.4,7.926223409080413,3,1\n', '51,4.5,1.5,12.753751383849565,3,1\n', '52,4.9,1.5,8.355485206218368,0,1\n', '53,4.0,1.3,11.20151786473049,0,1\n', '54,4.6,1.5,16.486228096114466,1,1\n', '55,4.5,1.3,8.620398718276542,4,1\n', '56,4.7,1.6,9.007624509523843,3,1\n', '57,3.3,1.0,7.092622342075035,0,1\n', '58,4.6,1.3,10.972259974504219,2,1\n', '59,3.9,1.4,11.307124682164698,3,1\n', '60,3.5,1.0,10.239711941637877,3,1\n', '61,4.2,1.5,14.841783103943044,1,1\n', '62,4.0,1.0,12.086951503454197,4,1\n', '63,4.7,1.4,15.90012063349484,1,1\n', '64,3.6,1.3,10.656516619537118,1,1\n', '65,4.4,1.4,13.835531997815501,1,1\n', '66,4.5,1.5,16.8131501573063,2,1\n', '67,4.1,1.0,14.379890097444436,1,1\n', '68,4.5,1.5,13.928972904260393,0,1\n', '69,3.9,1.1,14.382451929714382,2,1\n', '70,4.8,1.8,11.120413927535997,2,1\n', '71,4.0,1.3,16.259670690786393,1,1\n', '72,4.9,1.5,9.501289682530102,1,1\n', '73,4.7,1.2,11.656883551713335,1,1\n', '74,4.3,1.3,15.447398665907768,1,1\n', '75,4.4,1.4,9.267720605444616,3,1\n', '76,4.8,1.4,14.906482327486609,0,1\n', '77,5.0,1.7,13.365527218632167,0,1\n', '78,4.5,1.5,12.779075143553634,2,1\n', '79,3.5,1.0,15.351199331527937,4,1\n', '80,3.8,1.1,14.840736296068211,2,1\n', '81,3.7,1.0,7.027543244471426,3,1\n', '82,3.9,1.2,8.107372574547389,2,1\n', '83,5.1,1.6,16.767877368070522,0,1\n', '84,4.5,1.5,14.882043941247792,3,1\n', '85,4.5,1.6,11.006680130783657,1,1\n', '86,4.7,1.5,7.849465230033649,4,1\n', '87,4.4,1.3,11.071208106469857,4,1\n', '88,4.1,1.3,7.564388827415677,3,1\n', '89,4.0,1.3,12.282715471773672,3,1\n', '90,4.4,1.2,11.746316915937529,1,1\n', '91,4.6,1.4,8.30052575408047,0,1\n', '92,4.0,1.2,12.16434207746109,2,1\n', '93,3.3,1.0,14.293423128665179,3,1\n', '94,4.2,1.3,11.71912082585722,4,1\n', '95,4.2,1.2,7.0792618211135405,0,1\n', '96,4.2,1.3,7.1138899631420305,1,1\n', '97,4.3,1.3,12.982381388952934,2,1\n', '98,3.0,1.1,9.901891579514118,3,1\n', '99,4.1,1.3,16.201597140055185,2,1\n', '100,6.0,2.5,14.48768863028609,3,2\n', '101,5.1,1.9,9.900108051688097,1,2\n', '102,5.9,2.1,12.028583370432806,4,2\n', '103,5.6,1.8,9.488993089946433,3,2\n', '104,5.8,2.2,10.984912694395566,2,2\n', '105,6.6,2.1,15.266965594753668,3,2\n', '106,4.5,1.7,11.683694160797243,3,2\n', '107,6.3,1.8,15.270455718704053,0,2\n', '108,5.8,1.8,16.020736211335148,1,2\n', '109,6.1,2.5,12.589834522241112,0,2\n', '110,5.1,2.0,12.287106731257794,0,2\n', '111,5.3,1.9,7.698480868717254,4,2\n', '112,5.5,2.1,13.246683843360971,1,2\n', '113,5.0,2.0,8.120627865054463,2,2\n', '114,5.1,2.4,11.121838588372,0,2\n', '115,5.3,2.3,9.494800707127816,0,2\n', '116,5.5,1.8,11.443239345022866,2,2\n', '117,6.7,2.2,14.775144986611604,0,2\n', '118,6.9,2.3,14.687654458646788,3,2\n', '119,5.0,1.5,13.977043850265735,1,2\n', '120,5.7,2.3,15.04315705975904,2,2\n', '121,4.9,2.0,14.366570642292904,1,2\n', '122,6.7,2.0,12.150218586582033,3,2\n', '123,4.9,1.8,10.219986665025337,0,2\n', '124,5.7,2.1,7.941677972379946,4,2\n', '125,6.0,1.8,15.142867845852017,2,2\n', '126,4.8,1.8,13.195365652940087,4,2\n', '127,4.9,1.8,16.417750141887364,1,2\n', '128,5.6,2.1,14.757366041874457,2,2\n', '129,5.8,1.6,7.7458697604587075,3,2\n', '130,6.1,1.9,16.74317827810557,3,2\n', '131,6.4,2.0,13.121467672764744,2,2\n', '132,5.6,2.2,13.767838266424338,4,2\n', '133,5.1,1.5,14.653883205488905,0,2\n', '134,5.6,1.4,7.425553819896729,2,2\n', '135,6.1,2.3,9.930337693610028,4,2\n', '136,5.6,2.4,12.785681158208156,4,2\n', '137,5.5,1.8,11.583175474828195,1,2\n', '138,4.8,1.8,8.894276086607315,0,2\n', '139,5.4,2.1,13.600603165288161,3,2\n', '140,5.6,2.4,13.798630377122741,1,2\n', '141,5.1,2.3,16.475295885101804,1,2\n', '142,5.1,1.9,12.346420001985582,0,2\n', '143,5.9,2.3,13.4548068320682,3,2\n', '144,5.7,2.5,7.643523043062332,4,2\n', '145,5.2,2.3,7.159927770636358,0,2\n', '146,5.0,1.9,10.39785843284672,4,2\n', '147,5.2,2.0,15.174637698956268,2,2\n', '148,5.4,2.3,10.242003944476858,2,2\n', '149,5.1,1.8,16.315229496684843,2,2\n']

In [4]:
# Once again, this is more or less standard operating procedure; just a bit condensed
iris_data = []
for line in iris_lines:
  line = line[:-1]
  line = line.split(',')
  line.pop(0)
  processed_line = [ float(i) for i in line ]
  processed_line[-1] = int(processed_line[-1])
  processed_line[-2] = int(processed_line[-2])
  iris_data.append(processed_line)

In [5]:
import pandas as pd

df = pd.DataFrame(iris_data)
df

       0    1          2  3  4
0    1.4  0.2   8.438097  3  0
1    1.4  0.2  11.718959  0  0
2    1.3  0.2   9.344061  1  0
3    1.5  0.2  12.975980  3  0
4    1.4  0.2  15.399047  1  0
..   ...  ...        ... .. ..
145  5.2  2.3   7.159928  0  2
146  5.0  1.9  10.397858  4  2
147  5.2  2.0  15.174638  2  2
148  5.4  2.3  10.242004  2  2
149  5.1  1.8  16.315229  2  2

[150 rows x 5 columns]

In [6]:
df.columns = ["petal length", "petal width", "time when measured", "cur weather", "species"]
df.head()

   petal length  petal width  time when measured  cur weather  species
0           1.4          0.2            8.438097            3        0
1           1.4          0.2           11.718959            0        0
2           1.3          0.2            9.344061            1        0
3           1.5          0.2           12.975980            3        0
4           1.4          0.2           15.399047            1        0

In [35]:
# let's shuffle it (run once)
df = df.sample(frac=1, random_state=50)
df = df.reset_index(drop=True)
df.head()

   petal length  petal width  time when measured  cur weather  species
0           1.6          0.2           11.258255            4        0
1           1.7          0.2           13.117798            3        0
2           4.9          2.0           14.366571            1        2
3           4.5          1.5           12.779075            2        1
4           4.1          1.0           14.379890            1        1

In [8]:
# split into train and test
X = df.iloc[:,:-1]
y = df.iloc[:,-1]
train_X = X.iloc[0:100]
train_y = y.iloc[0:100]
test_X = X.iloc[100:150]
test_y = y.iloc[100:150]

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
# fit log reg model
log_reg = LogisticRegression(max_iter = 1000)
log_reg = log_reg.fit(train_X,train_y)

In [11]:
log_reg.score(test_X,test_y)

0.94

In [12]:
print("Model predictions:", list(log_reg.predict(test_X)))
print("Ground truth:     ", list(test_y))

Model predictions: [0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1, 0, 1, 0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 2, 0, 1, 2, 2, 0, 1, 1, 2, 1, 0, 0, 0, 2, 1, 2, 0]
Ground truth:      [0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1, 0, 2, 0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 2, 2, 0, 1, 1, 1, 1, 0, 0, 0, 2, 1, 2, 0]

In [13]:
from sklearn.feature_selection import SelectKBest, chi2
filter = SelectKBest(chi2, k=2)
# we just want to fit on training data
filter.fit(train_X, train_y)
# but apply the same transofrmation to both datasets
new_train_X = filter.transform(train_X)
new_test_X = filter.transform(test_X)

In [14]:
# convert everything to dataframes
new_train_X = pd.DataFrame(new_train_X)
new_test_X = pd.DataFrame(new_test_X)

In [15]:
remaining_features = filter.get_feature_names_out()
new_train_X.columns = remaining_features
new_test_X.columns = remaining_features

In [16]:
new_train_X.head()
# looks like our best ones are the actual features we had

   petal length  petal width
0           5.1          2.4
1           4.0          1.0
2           1.4          0.2
3           6.3          1.8
4           1.5          0.2

In [17]:
log_reg = LogisticRegression()
log_reg = log_reg.fit(new_train_X, train_y)
log_reg.score(new_test_X, test_y)

0.96

In [18]:
# looks like we improved our accuracy despite losing features

## BONUS

In [19]:
# download wine quality dataset directly
!wget https://archive.ics.uci.edu/static/public/186/wine+quality.zip
!unzip wine+quality.zip

--2024-06-19 18:42:29--  https://archive.ics.uci.edu/static/public/186/wine+quality.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘wine+quality.zip’

wine+quality.zip        [ <=>                ]  89.21K   453KB/s    in 0.2s

2024-06-19 18:42:30 (453 KB/s) - ‘wine+quality.zip’ saved [91353]

Archive:  wine+quality.zip
  inflating: winequality-red.csv
  inflating: winequality-white.csv
  inflating: winequality.names

In [20]:
# open up the files
opened_red_data = open('/content/winequality-red.csv','r')
opened_white_data = open('/content/winequality-white.csv','r')

# read the data and remove the names
red_data_lines = opened_red_data.readlines()
opened_red_data.close()
red_data_lines.pop(0)

# do the same for the white wines
white_data_lines = opened_white_data.readlines()
opened_white_data.close()
names = white_data_lines.pop(0)

In [21]:
# if the name type is not string (it is list) then we don't want to try this
if type(names) == str:
  # remove the " at the beginning and the "\n at the end.
  names = names[1:-2]
  names = names.split('";"')
  # add type to the names
  names.append("type")
names

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol',
 'quality',
 'type']

In [22]:
# here we make cleaned_red_data to eventually put all of our data
cleaned_red_data = []

for line in red_data_lines:
  # the data is separated by semicolons, so we split by those
  split_line = line.split(';')

  # for each of the features, we convert it into numbers
  for i in range(12):
    split_line[i] = float(split_line[i])

  # here, we add 0 for the class
  # 0 is for red wine
  split_line.append(0)

  # we add the line to cleaned_red_data
  cleaned_red_data.append(split_line)

In [23]:
# we do the same for white data
cleaned_white_data = []

for line in white_data_lines:
  split_line = line.split(';')

  for i in range(12):
    split_line[i] = float(split_line[i])

  # 1 is for white wine
  split_line.append(1)

  cleaned_white_data.append(split_line)

In [24]:
# import pandas under the nickname of pd
import pandas as pd

# add the lists together and join them into a dataframe
all_data = cleaned_red_data + cleaned_white_data
data = pd.DataFrame(all_data)
data.head()

     0     1     2    3      4     5     6       7     8     9    10   11  12
0   7.4  0.70  0.00  1.9  0.076  11.0  34.0  0.9978  3.51  0.56  9.4  5.0   0
1   7.8  0.88  0.00  2.6  0.098  25.0  67.0  0.9968  3.20  0.68  9.8  5.0   0
2   7.8  0.76  0.04  2.3  0.092  15.0  54.0  0.9970  3.26  0.65  9.8  5.0   0
3  11.2  0.28  0.56  1.9  0.075  17.0  60.0  0.9980  3.16  0.58  9.8  6.0   0
4   7.4  0.70  0.00  1.9  0.076  11.0  34.0  0.9978  3.51  0.56  9.4  5.0   0

In [25]:
# shuffle the data, using a random state of 0
data = data.sample(frac=1,random_state=0)
# here, we reset the indices to be in order and we don't want to get
# the old indices as a new column, so drop = True
data = data.reset_index(drop=True)
# give the columns names
data.columns = names
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,6.3,0.18,0.24,3.4,0.053,20.0,119.0,0.99373,3.11,0.52,9.2,6.0,1
1,6.8,0.14,0.18,1.4,0.047,30.0,90.0,0.99164,3.27,0.54,11.2,6.0,1
2,7.3,0.22,0.50,13.7,0.049,56.0,189.0,0.99940,3.24,0.66,9.0,6.0,1
3,7.6,0.67,0.14,1.5,0.074,25.0,168.0,0.99370,3.05,0.51,9.3,5.0,1
4,7.3,0.21,0.29,1.6,0.034,29.0,118.0,0.99170,3.30,0.50,11.0,8.0,1

In [26]:
X = data.iloc[:, 0:12]
X.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,6.3,0.18,0.24,3.4,0.053,20.0,119.0,0.99373,3.11,0.52,9.2,6.0
1,6.8,0.14,0.18,1.4,0.047,30.0,90.0,0.99164,3.27,0.54,11.2,6.0
2,7.3,0.22,0.50,13.7,0.049,56.0,189.0,0.99940,3.24,0.66,9.0,6.0
3,7.6,0.67,0.14,1.5,0.074,25.0,168.0,0.99370,3.05,0.51,9.3,5.0
4,7.3,0.21,0.29,1.6,0.034,29.0,118.0,0.99170,3.30,0.50,11.0,8.0

In [27]:
y = data["type"]

In [28]:
# separate out train, validation, and test x and y
train_X = X.iloc[:-600]
valid_X = X.iloc[-600:-200]
test_X = X.iloc[-200:]
train_y = y.iloc[:-600]
valid_y = y.iloc[-600:-200]
test_y = y.iloc[-200:]

In [29]:
# import relevant libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectKBest

In [30]:
# here, we have a function to run a model based on some particular hyperparameters
def run_model(feature_number, tree_count, max_dep):
  # we want to select the feature_number best features
  fil = SelectKBest(k=feature_number)
  fil = fil.fit(train_X, train_y)
  new_train_X = fil.transform(train_X)
  new_valid_X = fil.transform(valid_X)
  # make and train a random forest on training data then return the accuracy
  rf = RandomForestClassifier(n_estimators = tree_count, max_depth = max_dep)
  rf.fit(new_train_X, train_y)
  return rf.score(new_valid_X, valid_y)

In [31]:
# here we just define the posibilities for what hyperparameters we want
# you probably have different combinations depending on what you chose
feature_number_pos = [i for i in range(1, 11)]
tree_count_pos = [1, 5, 25, 100]
max_dep_pos = [1, 5, 10, 20]

In [32]:
# we want to get a list of the good combos
good_combos = []
# a triple nested for loop goes through all possible combos of hyperparameters
for fn in feature_number_pos:
  for tc in tree_count_pos:
    for md in max_dep_pos:
      # get the accuracy and print it out
      acc = run_model(fn, tc, md)
      # if we have good accuracy add it to our good combos
      if acc>=0.9875:
        print("good combo:")
        print("number of features:", fn)
        print("tree count", tc)
        print("max depth", md)
        print()
        good_combos.append([fn, tc, md])

good combo:
number of features: 7
tree count 25
max depth 10

good combo:
number of features: 8
tree count 25
max depth 10

good combo:
number of features: 8
tree count 25
max depth 20

good combo:
number of features: 8
tree count 100
max depth 10

good combo:
number of features: 9
tree count 100
max depth 20

good combo:
number of features: 10
tree count 25
max depth 5

good combo:
number of features: 10
tree count 25
max depth 20

good combo:
number of features: 10
tree count 100
max depth 10

In [33]:
# print out our good combos
print(good_combos)

[[7, 25, 10], [8, 25, 10], [8, 25, 20], [8, 100, 10], [9, 100, 20], [10, 25, 5], [10, 25, 20], [10, 100, 10]]

In [34]:
for gc in good_combos:
  fil = SelectKBest(k=gc[0])
  fil = fil.fit(train_X, train_y)
  new_train_X = fil.transform(train_X)
  new_test_X = fil.transform(test_X)
  # make and train a random forest on training data then return the accuracy
  rf = RandomForestClassifier(n_estimators = gc[1], max_depth = gc[2])
  rf.fit(new_train_X, train_y)
  print(gc, rf.score(new_test_X, test_y))

[7, 25, 10] 0.995
[8, 25, 10] 0.99
[8, 25, 20] 1.0
[8, 100, 10] 0.995
[9, 100, 20] 1.0
[10, 25, 5] 1.0
[10, 25, 20] 1.0
[10, 100, 10] 1.0